---
title: "Statistics education for PGT programmes at PaLS"
format: html
---

There are three statistics modules offered by postgraduate programmes at UCL Psychology and Language Sciences (PaLS). These are pitched at a fundamental, intermediate, and advanced level. Each postgraduate programme suggests a default module. All three modules share the same basic philosophy, which is to provide statistical literacy as a transferable skill, using state-of-the-art and freely available open-source software. That means that you can apply your acquired knowledge anywhere, and and at all times.

Depending on your experience and ability, it may be possible for you to switch to a module pitched at a *higher* level than the default for your program. By switching to a different module, you may enhance your learning opportunity and acquire new transferable skills. The module you take is also reflected on your degree transcript. As such, taking a more advanced module could be beneficial to later opportunities. The main thing to consider is which module is right for you at the time you are undertaking your postgraduate degree. There are always opportunities for later learning. In all modules, we aim to provide the best learning experience for our students. In the end, there should be no penalty for choosing the module that is right for you.
