---
title: "PALS PGT statistics module guidance"
format: html
---

Here, we aim to provide guidance to which module is right for you at the moment. This guidance is automated, and depends on your answers to the questions below. This is not an exam, and your answers are not recorded. There are no right or wrong answers for the purpose of suggesting a module. As we don't record answers, in requesting a switch to a more advanced level module, please download the "module_guidance.csv" file by clicking on the button at the bottom of this page. You should include this file when requesting a module change via email. 

By answering the questions below, we will provide you with automated guidance. This should not be taken as definite, as individual cases vary. The questions relate to four areas (interests, prior training, experience, and ability) and for each of these, your answers will be used to determine a level.

1.  Which module is the default in your programme?

```{ojs}
//| echo: false
//| panel: input
viewof default_module = Inputs.radio(new Map(
  [
    ["Fundamental module","fundamental"],
    ["Intermediate module", "intermediate"],
    ["Advanced module","advanced"]
  ] 
))
```

2.  Which module are you most interested in taking?

```{ojs}
//| echo: false
//| panel: input
viewof interest = Inputs.radio(new Map(
  [
    ["Fundamental module","fundamental"],
    ["Intermediate module", "intermediate"],
    ["Advanced module","advanced"]
  ] 
))
```

3.  How would you rate your technical/numerical ability (on a scale between 0 = very poor, and 100 = very good)?

```{ojs}
//| echo: false
//| panel: input
viewof self_rating = Inputs.range([0,100], {step: 1}, {value: 0})
```

4.  How would you rate your programming/coding ability (on a scale between 0 = very poor, and 100 = very good)?

```{ojs}
//| echo: false
//| panel: input
viewof self_rating_coding = Inputs.range([0,100], {step: 1}, {value: 0})
```

5.  How much prior statistics education have you had?

```{ojs}
//| echo: false
//| panel: input
viewof education = Inputs.radio([
    {label: "None",value: 0},
    {label: "Some (e.g. a single undergraduate statistics module or online course)",value: 1},
    {label: "Medium (e.g. two undergraduate statistics modules or online courses)",value: 2},
    {label: "Extensive (e.g. more than 2 undergraduate statistics modules or online courses)",value: 3}
  ], {format: x => x.label})
```

6.  When did you last receive statistics training?

```{ojs}
//| echo: false
//| panel: input
viewof education_when = Inputs.radio([
    {label: "Never", value: 0},
    {label: "More than 10 years ago",value: 1},
    {label: "Between 3 and 10 years ago", value: 2},
    {label: "Between 3 and 1 years ago",value: 3},
    {label: "Within the last year", value: 4}
  ], {format: x => x.label})
```

7.  Which analyses have you learned about?

```{ojs}
//| echo: false
//| panel: input
viewof analyses_learned = Inputs.checkbox(
  [
    {label: "Analysis-of-variance (ANOVA)", value: 2},
    {label: "Bivariate (or simple) regression", value: 1},
    {label: "Correlation", value: 1},
    {label: "Factor analysis", value: 3},
    {label: "Linear mixed-effects models", value: 3},
    {label: "Logistic regression", value: 2},
    {label: "Multiple regression", value: 2},
    {label: "Multivariate analysis-of-variance (MANOVA)", value: 3},
    {label: "Bivariate or simple regression", value: 1},
    {label: "Structural Equation Modeling (SEM)", value: 3},
    {label: "t-test", value: 1}
  ], {format: x => x.label})
```

8.  Which analyses have you used in practice?

```{ojs}
//| echo: false
//| panel: input
viewof analyses_used = Inputs.checkbox([
    {label: "Analysis-of-variance (ANOVA)", value: 2},
    {label: "Bivariate (or simple) regression", value: 1},
    {label: "Correlation", value: 1},
    {label: "Factor analysis", value: 3},
    {label: "Linear mixed-effects models", value: 3},
    {label: "Logistic regression", value: 2},
    {label: "Multiple regression", value: 2},
    {label: "Multivariate analysis-of-variance (MANOVA)", value: 3},
    {label: "Bivariate or simple regression", value: 1},
    {label: "Structural Equation Modeling (SEM)", value: 3},
    {label: "t-test", value: 1}
  ], {format: x => x.label})
```

9.  Which statistical software or programming language have you used?

```{ojs}
//| echo: false
//| panel: input
viewof software_used = Inputs.checkbox([
    {label: "C/C++", value: "language"},
    {label: "JAMOVI", value: "click"},
    {label: "JASP", value: "click"},
    {label: "julia", value: "language"},
    {label: "Matlab", value: "language"},
    {label: "Python", value: "language"},
    {label: "R", value: "R"},
    {label: "SAS", value: "script"},
    {label: "SPSS", value: "click"},
    {label: "STATA", value: "script"},
    {label: "other", value: "other"}
  ], {format: x => x.label})
```

10. If $Y = b \times X$, and $b=2$ and $X=3$, what is the value of $Y$?

```{ojs}
//| echo: false
//| panel: input
viewof algebra_1 = Inputs.radio(new Map(
  [
    ["1",0],
    ["3",0],
    ["4",0],
    ["6",1],
    ["9",0]
  ]
))
```

11. If $Y = a + b \times X$, then $X$ equals

```{ojs}
//| echo: false
//| panel: input
viewof algebra_2 = Inputs.radio(new Map(
  [
    ["Y",0],
    ["a/b",0],
    ["(Y-a)/b",1],
    ["a + b × Y",0],
    ["b × Y",0]
  ]
))
```

```{ojs}
//| echo: false

// viewof submit = Inputs.button("Submit")

function arraySum(arr) {
  return arr.reduce((total, current) => {
      return total + current;
  }, 0);
}
  
_interest = interest;

_software_used = software_used.reduce(function (
    count,
    currentValue
) {
    return (
        count[currentValue.value] ? ++count[currentValue.value] : (count[currentValue.value] = 1),
        count
    );
},
{});

_ability = {
  if(algebra_1 === 1 && algebra_2 === 1 && self_rating >= 70)  {
    yield {rating: 3, level: "advanced", explanation: "You indicate good technical ability and have grasp of basic algebra."};
  } else if (self_rating >= 50) {
    yield {rating: 2, level: "intermediate", "explanation": "You indicate a reasonable technical/numerical ability but incorrectly answered some of the basic algebra questions."};
  } else {
    yield {rating: 1, level: "fundamental", "explanation": "You indicate some lack of technical/numerical ability."};
  }
}

_programming = {
    if(self_rating_coding >= 70  && (_software_used["R"] == 1 || _software_used["language"] >= 1)) {
      yield {rating: 3, level: "advanced", explanation: "You indicate good programming ability and have experience with R or other programming languages."};
   } else if(self_rating_coding >= 50) {
      yield {rating: 2, level: "intermediate", explanation: "You indicate a reasonable programming ability."};
   } else {
      yield {rating: 1, level: "fundamental", explanation: "You indicate some lack of programming ability."};
   }
}

_analyses_learned = analyses_learned.reduce(function (
    count,
    currentValue
) {
    return (
        count[currentValue.value] ? ++count[currentValue.value] : (count[currentValue.value] = 1),
        count
    );
},
{});

_analyses_used = analyses_used.reduce(function (
    count,
    currentValue
) {
    return (
        count[currentValue.value] ? ++count[currentValue.value] : (count[currentValue.value] = 1),
        count
    );
},
{});



_education = {
if(education !== null && education_when !== null) {
  // (education/3)*(education_when/4)
  if (education.value >= 2 && education_when.value >= 2 && _analyses_learned["2"] >= 2) {
    yield {rating: 3, level: "advanced", "explanation": "You have received recent prior statistics education, which covered at least some intermediate topics."};
  } else if (education.value == 0 || education_when.value < 2) {
    yield {rating: 1, level: "fundamental", explanation: "You have not received prior statistics education, or this was a long time ago."};
  } else {
    yield {rating: 2, level: "intermediate", explanation: "You have received some prior statistics education in the not too distant past."};
  } 
} else {
  yield null;
}
}

_experience = {
  let explnt = "";
  if(_analyses_used["1"] >= 2 && _analyses_used["2"] >= 2) {
    explnt += "You have experience with at least some intermediate analyses";
    if(_analyses_used["3"] >= 1) {
      explnt += " and advanced analyses";
    }
    if (_software_used["R"] === 1) {
      explnt += ", as well as R.";
    } else if (_software_used["language"] >= 1 || _software_used["script"] >= 1) {
      explnt += ", as well as some programming languages or statistical scripting languages."
    }
    yield {rating: 3, level: "advanced", explanation: explnt};
  } else if ((_analyses_used["1"] <= 2 && _analyses_used["2"] == 0 && _analyses_used["3"] == 0) || (_analyses_used["1"] === undefined && _analyses_used["2"] === undefined && _analyses_used["3"] === undefined)) {
    explnt += "You have experience with at most some basic analyses.";
    yield {rating: 1, level: "fundamental", explanation: explnt}
  } else {
    yield {rating: 2, level: "intermediate", explanation: "You have some experience in applying statistical analyses."};
  }
}

mytab = {
  if (interest === null || education === null || education_when === null || algebra_1 === null || algebra_2 === null) {
  yield []
} else {
  yield [
    {area: "interest", level: _interest, reason: ""},
    {area: "training", level: _education.level, reason: _education.explanation},
    {area: "experience", level: _experience.level, reason: _experience.explanation},
    {area: "technical", level: _ability.level, reason: _ability.explanation},
    {area: "programming", level: _programming.level, reason: _programming.explanation}
  ]
  }
}

html`<h2>Guidance</h2>`

viewof table = Inputs.table(mytab)


// chart = vl.markBar() // Make a bar chart 
//   .data([{name: "interests", value: _interest},
//          {name: "ability", value: _ability},
//          {name: "training", value: _education},
//          {name: "experience", value: _experience}])
//   .encode(
//     vl.y().fieldO("name"),        // Show letters in sequential order on the x-axis
//     vl.x().fieldQ("value"), //.axis({ format: "%" }), // Show frequency on the y-axis, formatted as percent
//     // vl.color().value(yourColor)   // Set the bar color
//   )
//   .render()

advice = {
  // submit;
  let advice_string = "";
  if(interest === null || education === null || education_when === null || algebra_1 === null || algebra_2 === null) {
    advice_string += "Please answer all questions.";
  } else {
    if (interest === "advanced") {
      advice_string += "You indicate you are interested in taking the Advanced module. "
    // check prior education 
      if(_education.level === "advanced" && _ability.level === "advanced" && _experience.level === "advanced" && _programming.rating >= 2) {
      // perfect score
        advice_string += "Based on your stated prior education and experience with statistical analyses, as well as your (subjective) technical and programming ability, we believe this is likely the right choice for you. As such, the advice is to take the Advanced module."
      } else if (_education.rating >= 1 && _ability.rating === 3 && _experience.rating === 3 && _programming.rating === 3) {
        advice_string += "Whilst your stated prior education is more suitable for the Intermediate module, your stated experience with statistical analyses and your (subjective) technical and programming ability indicate you may be ready to take the Advanced module. As such, the advice is to consider taking the Advanced module, although the Intermediate module might be more suitable to you."
      } else if(_education.rating === 3 && _ability.rating === 3 && _experience.rating >= 1 && _programming.rating === 3 && _software_used["R"] === 1) {
        advice_string += "You seem to have experience mostly with the more basic statisical analyses. However, your stated prior education and (subjective) technical and programming ability, as well asw your experience with R, indicate you may be ready to take the Advanced module. As such, the advice is to consider taking the Advanced module, although the Intermediate module might be more suitable to you."
      } else if(_education.rating >= 2 && _ability.rating === 3 && _experience.rating >= 1 && _programming.rating === 3) {
        advice_string += "You seem to have experience mostly with the more basic statisical analyses. However, your stated prior education and (subjective) technical and programming ability indicate you are likely ready to take the Advanced module. As such, the advice is to consider taking the Advanced module, although the Intermediate module might be more suitable to you."
      } else if (_ability.rating === 3 && _education.rating >= 1 && _experience.rating >= 1 && _programming.rating === 3) {
        advice_string += "Your prior statistics education and experience is more suitable to the Intermediate module. However, your (subjective) technical and programming ability indicate you could be ready to take the Advanced module. As such, the advice is take the Intermediate module, but you can consider taking the Advanced module if you feel confident you can quickly grasp the statistical concepts."
      } else if (_education.rating === 3 && _experience.rating === 3 && _programming.rating < 3 && _ability.rating < 3) {
        advice_string += "However, your (subjective) technical and programming ability indicates the Advanced module may not be suitable for you. That said, your stated prior education and experience with statistical analyses indicate you could be ready to take the Advanced module. Our advice is to take the Intermediate module, although you could consider taking the Advanced module if you are willing to put in additional effort to improve your technical and programming ability."
      } else if (_education.rating === 2 && _experience.rating === 3 && _programming.rating < 3 && _ability.rating < 3) {
        advice_string += "However, your (subjective) technical and programming ability indicates the Advanced module may not be suitable to you. Nevertheless, your stated prior education and experience with statistical analyses indicate you could be ready to take the Advanced module. Our advice is to take the Intermediate module, although you could consider taking the Advanced module if you are willing to put in additional effort to improve your technical and programming ability."
      } else if (default_module === "intermediate") {
        advice_string += "However, your answers indicate that this is likely not the best choice for you. As such, our recommendation is to take the Intermediate module." 
      } else {
        advice_string += "However, your answers indicate that this is likely not the best choice for you. As such, our recommendation is to take the Intermediate or Fundamental module." 
      }
    } else if (_interest === "intermediate") {
    advice_string += "You indicate you are interested in taking the Intermediate module. "
    if(_education.rating === 3 && _ability.rating === 3 && _experience.rating === 3 && _programming.rating === 3) {
      advice_string += "Your prior statistics education and experience, as well as your (subjective) technical and programming ability, indicate that the Advanced module may also be the right choice for you. Our advise is therefore to take the Intermediate module, although you could consider the Advanced module as well."
      } else if(_education.rating >= 1 && _ability.rating >= 2 && _experience.rating >= 1 && _programming.rating >= 2) {
      // perfect score
        advice_string += "Based on your stated prior education and experience with statistical analyses, as well as your (subjective) technical and programming ability, we believe this is likely the right choice for you. As such, the advice is to take the Intermediate module."
      } else if( _ability.rating === 1 && _programming.ability === 1 && default_module === "fundamental") {
        advice_string += "However, your (subjective) technical and programming ability indicates that you may struggle with some of the aspects of this module. As such, the advice is to take the Fundamental module. You can consider the Intermediate module, but you should realise that learning to program in R may be difficult and require additional effort."
      } else {
        advice_string += "However, your (subjective) technical and programming ability indicates that you may struggle with some of the aspects of this module."
      }
    } else if(_interest === "fundamental" && default_module !== "fundamental") {
      advice_string += "You indicate you are interested in taking the Fundamental module. However, the default module of your programme is set at a higher level, and you can not switch to the Fundamental module."
    } else if(_interest === "fundamental") {
      advice_string += "You indicate you are interested in taking the Fundamental module."
      if(_education.rating === 3 && _ability.rating === 3 && _experience.rating === 3 && _programming.rating === 3) {
        advice_string += " Your stated prior education and experience with statistical analyses, as well as your (subjective) technical and programming ability, indicate that the Advanced module may also be the right choice for you. Our advise is therefore to take the Fundamental module, although you may consider the Advanced module. "
      } else if(education >= 2 && education_when > 1 && _programming.rating >= 2) {
        advice_string += " As you indicate relevant and (at least somewhat) recent prior statistics education, as well as some programming/coding ability, you could also consider taking the Intermediate module."
      } else {
        advice_string += " As this is the default module in your programme, we recommend you stick to the Fundamental module."
      }
    }
  }
  yield advice_string;
}
html`<p></p><p>${advice}</p>`
```

```{ojs}
//| echo: false
//| panel: input

import {button} from "@jeremiak/download-data-button"

analyses_learned_text = analyses_learned.map(function(x){return x.label}).join(",");
analyses_used_text = analyses_used.map(function(x){return x.label}).join(",");
software_used_text = software_used.map(function(x){return x.label}).join(",");
education_text = { if(education != null) {yield education.label} else {yield ""}}
education_when_text = {if(education_when != null) {yield education_when.label} else {yield ""}}


save_data = {
  if(mytab.length > 1) {yield [
  {advice: advice},
  {domain: "training", level: mytab[1].level, reason: mytab[1].reason},
  {domain: "experience", level: mytab[2].level, reason: mytab[2].reason},
  {domain: "technical", level: mytab[3].level, reason: mytab[3].reason},
  {domain: "programming", level: mytab[4].level, reason: mytab[4].reason},
  {question: "Default module", value: default_module},
  {question: "Interested in", value: interest},
  {question: "Technical ability", value: self_rating},
  {question: "Programming ability", value: self_rating_coding},
  {question: "Prior education", value: education_text},
  {question: "Prior education when", value: education_when_text},
  {question: "Analyses learned", value: analyses_learned_text},
  {question: "Analyses used", value: analyses_used_text},
  {question: "Software used", value: software_used_text},
  {question: "Algebra 1", value: algebra_1},
  {question: "Algebra 2", value: algebra_2}
]} else {
  yield [{}];
}
}
button(save_data, "module_guidance.csv")
```
