---
title: "Switching modules"
format: html
---

You can request to switch to a higher-level module. This requires approval from the Programme Director. The deadline for switching modules is the end of induction week, so you don't miss vital teaching due to changing modules after teaching started. The pace of the modules is high and it will be difficult to catch up on missed initial content. Therefore, changing modules is not possible past the end of the first week of teaching.

The procedure for switching modules is as follows:

1.  Read the "Modules overview" page carefully.
2.  Complete the questions in the "Module guidance" page read the advice carefully. Download the "module_guidance.csv" file by clicking on the button at the bottom of the page.
3.  Contact Hannah Spikesley via [email](mailto:h.spikesley@ucl.ac.uk). Please use "PGT Statistics request for module change" as the subject line. In the email, please state your PGT programme and the module you would like to switch to. Also attach the downloaded file with your answers and advice.
4.  Hannah will contact your Programme Director to arrange discussion of your request.
5.  Your Programme Director will confirm to Hannah whether you can switch and if so, your request is processed. Note that you only need to complete these steps if you want to switch to a module.
